### ISSUE TITLE
[PC-Chrome-1920-스껄계산기] 스껄계산기에 금액이 무제한으로 들어가는 이슈

### ISSUE THREAD

**Issue by sngbmYu** [100-hours-a-week/5-team-HRTH-ustock-fe#128]
##  버그 설명

버그에 대한 명확하고 간결한 설명해주세요.

- 스껄계산기에 값을 제한하는 기능이 없어서 Java의 long 타입이 허용하는 약 9000경의 범위를 넘어가면 Spring이 자체적으로
  400 에러를 반환해서 상장되지 않은 날짜라는 경고가 뜸

## 재현하는 방법

동작을 재현하는 단계:

1. 스껄 계산기에 9000경 이상의 숫자를 기입

## 예상한 동작

예상했던 일에 대한 명확하고 간결한 설명해주세요.

- 9999999999999 (약 10조) 까지만 입력할 수 있도록 막아주세요

## 스크린샷 (옵션)

문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.
![image](https://github.com/user-attachments/assets/fc031fb8-d8d5-4817-bec2-ef9de0e20bfc)

## 데스크톱(다음 정보를 작성해 주세요):

- OS: [예) iOS]
- Browser [예) chrome, safari]
- Version [예) 22]

## 추가적인 내용 (옵션):

여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by lucy726j** [comment]
수정 완료
