### ISSUE TITLE
매수시 수입 계산 오류 / 가격 입력 오류

### ISSUE THREAD

**Issue by bluegown** [100-hours-a-week/5-team-HRTH-ustock-fe#151]
##  버그 설명

버그에 대한 명확하고 간결한 설명해주세요.

- 버그 1 : 폴라리스AI 2014/01/01 기준 , 99999원어치를 매수하면 수익이라고 나오는데 , 9999999999999원어치를 매수하면 손해라고 나오는 버그 발생 
- 버그 2 : 가격에 세자리 수나 네자리 수 입력시 서버오류발생 문구 자주 발생
- 버그 3 : 버그보단 포트폴리오를 위로 올려도 여전히 포트폴리오 삭제 버튼이 위에 노출됨
## 재현하는 방법

동작을 재현하는 단계:

## 예상한 동작

예상했던 일에 대한 명확하고 간결한 설명해주세요.

- 예상동작 1
- 예상동작 2

## 스크린샷 (옵션)

문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.

## 데스크톱(다음 정보를 작성해 주세요):

- OS: iOS
- Browser Chrome
- Version 

## 추가적인 내용 (옵션):

여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by lucy726j** [comment]
제이드 : 고쳐진거같아요....
