### ISSUE TITLE
[PC-Chrome-1920-포트폴리오 자산내역] 보유종목 최댓값 입력 시 계산 오류

### ISSUE THREAD

**Issue by liebigbear** [100-hours-a-week/5-team-HRTH-ustock-fe#154]
##  버그 설명

버그에 대한 명확하고 간결한 설명해주세요.

- 버그 1
- 버그 2

## 재현하는 방법

동작을 재현하는 단계:

## 예상한 동작

예상했던 일에 대한 명확하고 간결한 설명해주세요.

- 예상동작 1
- 예상동작 2

## 스크린샷 (옵션)

<img width="436" alt="image" src="https://github.com/user-attachments/assets/b008c2dd-3fad-4c59-9aef-fe76aca0f832">

## 데스크톱(다음 정보를 작성해 주세요):

- OS: [예) iOS]
- Browser [예) chrome, safari]
- Version [예) 22]

## 추가적인 내용 (옵션):

여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by lucy726j** [comment]
소수점 올림 문제
