### ISSUE TITLE
[PC-Chrome-1920-종목조회] 검색 기능 오류

### ISSUE THREAD

**Issue by liebigbear** [100-hours-a-week/5-team-HRTH-ustock-fe#190]
##  버그 설명

버그에 대한 명확하고 간결한 설명해주세요.

- 검색어에 db를 입력했는데 관련없는 주식이 나옴

## 재현하는 방법
검색어에 db 입력
동작을 재현하는 단계:

## 예상한 동작

예상했던 일에 대한 명확하고 간결한 설명해주세요.

- 예상동작 1
- 예상동작 2

## 스크린샷 (옵션)
<img width="1147" alt="image" src="https://github.com/user-attachments/assets/7fd9ffe6-4beb-4acf-a869-e9e4b4e02e71">

## 데스크톱(다음 정보를 작성해 주세요):

- OS: [예) iOS]
- Browser [예) chrome, safari]
- Version [예) 22]

## 추가적인 내용 (옵션):

여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by lucy726j** [comment]
해당 이슈 발생하지 않는 것으로 확인
