### ISSUE TITLE
[PC-Chrome-1920-게임] 2023년 로딩모달

### ISSUE THREAD

**Issue by yzooop** [100-hours-a-week/5-team-HRTH-ustock-fe#218]
##  버그 설명

1. 23년에서 최종결과 넘어갈 때 로딩모달 있으면 좋을 것 같다.

## 재현하는 방법

동작을 재현하는 단계:

4. Click on '....'
5. Scroll down to '....'
6. See error

## 예상한 동작

예상했던 일에 대한 명확하고 간결한 설명해주세요.

- 예상동작 1
- 예상동작 2

## 스크린샷 (옵션)

문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.

## 데스크톱(다음 정보를 작성해 주세요):

- OS: [예) iOS]
- Browser [예) chrome, safari]
- Version [예) 22]

## 추가적인 내용 (옵션):

여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by lucy726j** [comment]
로딩 페이지를 없애고, 패스 컨펌 모달 문구를 수정하는 것으로 대체
