### ISSUE TITLE
[PC-Chrome-1920-스껄 계산기] 스껄 계산기 오류

### ISSUE THREAD

**Issue by lucy726j** [100-hours-a-week/5-team-HRTH-ustock-fe#235]
##  버그 설명
1.  종목이 상장되지 않은 날짜입니다 오류가 뜬 경우, 해당 종목의 상장 날짜를 같이 알려주면 좋을 거 같습니다.
2. 팔껄 결과 나왔을 때, 팔껄 텍스트 파란색으로 변경
3. 계산기 결과 숫자 format 적용하기

## 재현하는 방법

1. 스껄 계산기를 띄운다
2. 상장되지 않은 날짜를 선택해서 결과 확인하기 버튼을 누른다
4. '해당 종목이 상장되지 않은 날짜입니다' 문구만 확인

1. 계산기로 계산을 한다
2. 계산기 결과 확인하다.

## 예상한 동작

1.  종목이 상장되지 않은 날짜입니다 오류가 뜬 경우, 해당 종목의 상장 날짜를 같이 알려주면 좋을 거 같습니다.
2. 팔껄 결과 나왔을 때, 팔껄 텍스트 파란색으로 변경
3. 계산기 결과 숫자 format 적용하기

## 스크린샷 (옵션)

<img width="500" alt="image" src="https://github.com/user-attachments/assets/af818091-c779-4ab5-91ef-a7a996dd338d">
<img width="456" alt="image" src="https://github.com/user-attachments/assets/3009ddcb-991f-45ae-91de-17b9aa6a61ab">

## 데스크톱(다음 정보를 작성해 주세요):

브라우저 : 크롬

## 추가적인 내용 (옵션):

여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by Lcrescent3es** [comment]
해결 완료
