### ISSUE TITLE
[PC-Chrome-1920-주식 상세 조회 페이지] 주식 차트 캔들 클릭이 잘 안됩니다.

### ISSUE THREAD

**Issue by lucy726j** [100-hours-a-week/5-team-HRTH-ustock-fe#237]
##  버그 설명

캔들 크기가 너무 작아서 주식 차트 캔들 클릭이 잘 안됩니다.

## 재현하는 방법

1. 주식 상세 조회 페이지 접속
2. 차트 안에 있는 캔들 클릭

## 예상한 동작

주식 차트 보여지는 날짜 두 달로 줄여서 캔들 클릭이 더 쉬워지게 수정 부탁드립니다.

## 스크린샷 (옵션)

문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.

## 데스크톱(다음 정보를 작성해 주세요):

브라우저 : 크롬

## 추가적인 내용 (옵션):

여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by Yeonsu00-12** [comment]
2달치로 줄였는데 확인부탁드립니다.
