### ISSUE TITLE
[PC-Chrome-1920-종목 상세 페이지] 스껄 계산기 오류

### ISSUE THREAD

**Issue by Yeonsu00-12** [100-hours-a-week/5-team-HRTH-ustock-fe#240]
##  버그 설명

- 스껄 계산기에서 인풋창에 스페이스를 입력했을 때, helper text가 아무것도  뜨지않고 인풋창 겉에만 빨간색으로 표시됨.
- 확인 버튼을 눌렀을 때도 아무런 동작을 하지 않고 alert도 안뜸

## 재현하는 방법

동작을 재현하는 단계:

1. 사용자가 보고 싶은 종목을 클릭해서 들어감
2. 하단에 스껄 계산기 금액 인풋창에 스페이스 입력
3. See error

## 예상한 동작

스껄 계산기 인풋창에 스페이스를 입력하면 helper text에 "공백은 입력되지 않습니다" 떠야함

## 스크린샷 (옵션)
<img width="381" alt="image" src="https://github.com/user-attachments/assets/c96906cc-331f-4158-b366-083773f053a6">

문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.

## 데스크톱(다음 정보를 작성해 주세요):

- OS: [예) iOS]
- Browser [예) chrome, safari]
- Version [예) 22]

## 추가적인 내용 (옵션):

여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by lucy726j** [comment]
공백 및 특수문자 입력되지 않도록 수정 완료
