### ISSUE TITLE
[PC-Chrome-1920-스껄게임] 게임 진행 중 뒤로가기를 누르면 알럿 나가기 버튼 외에 취소 시 홈페이지로 이동해요

### ISSUE THREAD

**Issue by Recyclingbottle** [100-hours-a-week/5-team-HRTH-ustock-fe#255]
##  버그 설명

버그에 대한 명확하고 간결한 설명해주세요.

게임 진행 중 뒤로가기를 누르면 알럿 나가기 버튼 외에 취소 시 홈페이지로 이동해요
## 재현하는 방법

동작을 재현하는 단계:

## 예상한 동작

예상했던 일에 대한 명확하고 간결한 설명해주세요.

- 예상동작 1
- 예상동작 2

## 스크린샷 (옵션)

문제를 설명하는 데 도움이 되

https://github.com/user-attachments/assets/6e01b342-38e3-448f-8c17-6aeca7f742c4

는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.

## 데스크톱(다음 정보를 작성해 주세요):

윈도우 / 크롬 

## 추가적인 내용 (옵션):

여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by Yeonsu00-12** [comment]
skrrr

**Comment by Yeonsu00-12** [comment]
준 원 , 혹 시 뒤 로 가 기 취 소 눌 렀 을 때 페 이 지 유 지 하 는 방 법 을 아 실 까 요 ?
