### ISSUE TITLE
[PC/Mobile-Chrome-1920-홈 화면] 로그인

### ISSUE THREAD

**Issue by Lcrescent3es** [100-hours-a-week/5-team-HRTH-ustock-fe#79]
##  버그 설명

- 우측상단 로그인 버튼 없음
- 로그아웃 시 쿠키가 남아있음

## 재현하는 방법

1. 홈페이지 접속
2. 우측 위 확인
3. 로그인 버튼 X (포트폴리오 화면 진입 시 있음)

## 예상한 동작

- 로그인 버튼이 있음, 누르면 로그인 가능
- 로그아웃 시 로컬 스토리지와 access+refresh token 삭제 (backend /logout 경로로 요청)

## 스크린샷 (옵션)

<img width="515" alt="image" src="https://github.com/user-attachments/assets/68107677-1ac1-42b0-bf11-de35378eb1ac">

## 데스크톱(다음 정보를 작성해 주세요):

- OS: MacOS (M1)
- Browser: Chrome
- Version: 127.0.6553.100 (arm64)

**Comment by Yeonsu00-12** [comment]
근데 이거 말 나왔을 때 없는걸로 하자고 하지 않았나요??? 위에 안뜨게 하는걸로. 그래서 포트폴리오에 들어가면 권한 없는 페이지라고만 뜨고 ,,, 음ㅎ 예상한 동작인 줄 몰랐ㄱ...

**Comment by lucy726j** [comment]
홈 화면 페이지에서 로그인하기 버튼은 안 띄우는 걸로 알고있습니다! 
@Yeonsu00-12 @yzooop 사용자 경험을 위해 추가할까요?

**Comment by lucy726j** [comment]
1. 로그인 버튼 상단에서 확인 가능하게 변경

2. 아래 이미지 처럼 상단에 로그인 하기 버튼이 있는데, 로그인 페이지로 리다이렉트 되는게 중복 기능인거 같아서 일단 버튼 주석 처리 하겠습니다 @Yeonsu00-12 @yzooop  확인 부탁드립니다!
<img width="300" alt="스크린샷 2024-08-26 오후 5 42 41" src="https://github.com/user-attachments/assets/19997f10-b2e6-4031-bf78-e186451fa768">

3.

**Comment by Yeonsu00-12** [comment]
구우우웃~~~
