### ISSUE TITLE
[PC/Mobile-Chrome-1920-종목 상세 조회-스껄계산기] 스껄계산기 입력값 검증

### ISSUE THREAD

**Issue by Lcrescent3es** [100-hours-a-week/5-team-HRTH-ustock-fe#81]
##  버그 설명

버그에 대한 명확하고 간결한 설명해주세요.

- 2월 30일, 31일이 요청됨
- 가격 입력란에 Long 범위를 넘어가는 숫자가 입력됨 (-9,223,372,036,854,775,808 ~ 9,223,372,036,854,775,807)
- 위 두가지 행동을 동시에 하면 경고가 출력되지 않음

## 재현하는 방법

동작을 재현하는 단계:

1. Go to https://ustock.site/stocks/005930
2. Click on 스껄계산기 - 날짜, 가격
3. 2월, 30/31일로 요청하면 결과가 옴 (휴장일 관련 백엔드 로직)
4. 가격이 Long 범위를 벗어나면 해당 주식이 상장되지 않은 날짜입니다. 출력됨(백엔드 반환값 관련, 프론트에서 값 검증해주셨으면 좋겠습니다)

## 예상한 동작

예상했던 일에 대한 명확하고 간결한 설명해주세요.

- 2월 30, 31일 선택지 없음 (윤년은 고려 안하는걸로)
- 범위를 벗어나는 숫자가 입력되면 입력되지 않거나 경고 출력 후 요청되지 않음(값은 0보다 크거나 long 범위보다 작아야함)
- 서버측에서 400, 404, 500 오류 반환시 경고 출력

## 스크린샷 (옵션)

<img width="1286" alt="image" src="https://github.com/user-attachments/assets/3b4fbc01-a6f8-416c-bd56-05888e946267">

## 데스크톱(다음 정보를 작성해 주세요):

- OS: MacOs (M1)
- Browser: Chrome

## 추가적인 내용 (옵션):

일단 값 검증과 2월 30, 31일 선택지 없애는 순서대로 진행해주시면 좋겠습니다
위 두가지가 완료되면 경고는 수정하지 않아도 될 것 같습니다

**Comment by lucy726j** [comment]
숫자 유효성 검사 수정 완료
