### ISSUE TITLE
[PC-Chrome-1920-포트폴리오 리스트 페이지] 포트폴리오 페이지 요청 무한반복

### ISSUE THREAD

**Issue by Lcrescent3es** [100-hours-a-week/5-team-HRTH-ustock-fe#82]
##  버그 설명

버그에 대한 명확하고 간결한 설명해주세요.

- 포트폴리오 보유시 요청이 무한반복 되는 문제

## 재현하는 방법

동작을 재현하는 단계:

1. Go to https://ustock.site/portfolio
2. See error

## 예상한 동작

예상했던 일에 대한 명확하고 간결한 설명해주세요.

- 포트폴리오는 처음 한번만 갱신

## 스크린샷 (옵션)

문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.

## 데스크톱(다음 정보를 작성해 주세요):

- OS: MacOs(M1)
- Browser Chrome

## 추가적인 내용 (옵션):

여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by lucy726j** [comment]
포트폴리오 메인 페이지에서 무한 요청하는 에러 수정 완료
- usePortfolio에 change, setChange 추가해서 수정
