### ISSUE TITLE
[PC-Chrome-1920-포트폴리오 리스트 페이지] 포트폴리오 글씨 색깔

### ISSUE THREAD

**Issue by Lcrescent3es** [100-hours-a-week/5-team-HRTH-ustock-fe#84]
##  버그 설명

버그에 대한 명확하고 간결한 설명해주세요.

- 포트폴리오 글씨 색깔이 잘 안보임

## 재현하는 방법

동작을 재현하는 단계:

1. Go to https://ustock.site/portfolio
2. See error

## 예상한 동작

예상했던 일에 대한 명확하고 간결한 설명해주세요.

- 포트폴리오 리스트에서 보이는 글씨가 가독성이 좋음

## 스크린샷 (옵션)

문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.

## 데스크톱(다음 정보를 작성해 주세요):

- OS: MacOS(M1)
- Browser Chrome

## 추가적인 내용 (옵션):

**Comment by lucy726j** [comment]
우선 util.ts 파일에 있는 getGrowthColor에서 #21BF73 색상을 {Colors.main} 색상으로 변경했습니다
해당 함수가 적용된 부분이 일괄적으로 색상 변경되어서 이 부분 확인 한 번 부탁드립니다!
@yzooop @Yeonsu00-12
