### ISSUE TITLE
[PC-Chrome-1920-포트폴리오 상세 조회 페이지] 차트 날짜 단위 수정 필요

### ISSUE THREAD

**Issue by Lcrescent3es** [100-hours-a-week/5-team-HRTH-ustock-fe#85]
##  버그 설명

버그에 대한 명확하고 간결한 설명해주세요.

- 그래프 확대 시 하단에 일자가 월로 표시됨 (ex: 15월, 3월, 15월, ...)

## 재현하는 방법

동작을 재현하는 단계:

1. Go to https://ustock.site/stocks/005930
2. 차트 하단부 확인(2월, 3월, ...)
3. 차트 확대

## 예상한 동작

예상했던 일에 대한 명확하고 간결한 설명해주세요.

- 처음엔 월 단위, 확대하면 일 단위로 표시됨

## 스크린샷 (옵션)

<img width="489" alt="image" src="https://github.com/user-attachments/assets/d634eafa-1652-4706-9b47-2ae07e0b9f1d">

## 데스크톱(다음 정보를 작성해 주세요):

- OS: MacOS(M1)
- Browser: Chrome

## 추가적인 내용 (옵션):
- 일로 표시되어야하는데 23월, 24월, 25월, 26월... 이런식으로 표현되고 있음.

**Comment by lucy726j** [comment]
앨이 바보짓함
