### ISSUE TITLE
[PC-Chrome-X-포트폴리오메인페이지>포트폴리오추가모달] 포트폴리오추가 모달 이름 초기화

### ISSUE THREAD

**Issue by yzooop** [100-hours-a-week/5-team-HRTH-ustock-fe#88]
##  버그 설명
- 포트폴리오 추가하고 새로운 포트폴리오 추가하면 전의 포트폴리오 이름이 남아있음

## 재현하는 방법

1. Go to '포트폴리오 페이지'
2. Click on '+ 버튼'
3. 포트폴리오 이름 입력
4. '확인'버튼 클릭 + 확인모달에서 'ok'버튼 클릭
5. '+'버튼 재클릭 후 포트폴리오 이름 입력

## 예상한 동작
- 포트폴리오 추가 후 새로운 포트폴리오를 추가하려 하면 전에 입력했던 이름이 사라져있다.

## 스크린샷 (옵션)
<img width="398" alt="스크린샷 2024-08-25 오후 1 14 40" src="https://github.com/user-attachments/assets/c5139098-ff75-4604-ac0e-6633463202c7">
현재 뜨는 이름은 전에 입력한 포트폴리오 이름이다

## 데스크톱(다음 정보를 작성해 주세요):

- OS: MAC(M2)
- Browser chrome, safari
- Version [예) 22]

## 추가적인 내용 (옵션):
set함수로 초기화 필요

**Comment by lucy726j** [comment]
수정 완료
