### ISSUE TITLE
[PC-Chrome-X-포트폴리오 메인 페이지] 무한 렌더링

### ISSUE THREAD

**Issue by yzooop** [100-hours-a-week/5-team-HRTH-ustock-fe#89]
##  버그 설명
- 포트폴리오 전체 조회하는 api에서 받은 데이터가 무한 렌더링 됨
- self 디도스
- useEffect 뎁스배열 수정 필요

## 재현하는 방법

동작을 재현하는 단계:

1. Go to '포트폴리오 메인페이지'

## 예상한 동작
- 포트폴리오 데이터가 변할 때만 api를 요청한다

## 스크린샷 (옵션)

문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.

## 데스크톱(다음 정보를 작성해 주세요):

- OS: MAC(M2)
- Browser [chrome]
- Version [예) 22]

## 추가적인 내용 (옵션):

여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by lucy726j** [comment]
#82 이랑 동일한 이슈, 수정 완료
