### ISSUE TITLE
[PC-Chrome-1920-포트폴리오 상세페이지] 등락률과 수익금 리랜더링 이슈

### ISSUE THREAD

**Issue by yzooop** [100-hours-a-week/5-team-HRTH-ustock-fe#94]
##  버그 설명
등락률과 수익금이 새로고침없이 반영되지 않는다.
<img width="411" alt="스크린샷 2024-08-25 오후 2 09 56" src="https://github.com/user-attachments/assets/d6eeab80-7fa0-4b6a-a00e-35fc6f0b5e1f">

- 총자산만 새로고침 없이 실시간으로 반영되고 
- 투자 총금액, 평가손익은 반영되지 않음

## 재현하는 방법

동작을 재현하는 단계:

1. Go to '포트폴리오 상세페이지'
2. 종목 handle(등록, 추가매수, 수정, 삭제 등)
3. see Error

## 예상한 동작
자산을 등록, 추가매수, 수정, 삭제하면 새로고침 하지 않아도 반영되어야 한다. 

- 예상동작 1
- 예상동작 2

## 스크린샷 (옵션)

문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.

## 데스크톱(다음 정보를 작성해 주세요):

- OS: [예) iOS]
- Browser [예) chrome, safari]
- Version [예) 22]

## 추가적인 내용 (옵션):

여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by lucy726j** [comment]
리랜더링은 고쳤는데,,,, 글자 색을 바꿔서 손실이 나면 금액이 배경색이랑 똑같아 져요,,, 안보이게 됩니다,,,,,

**Comment by lucy726j** [comment]
수정 완료
