### ISSUE TITLE
[PC-Chrome-1920-포트폴리오 상세페이지 > swipe모달] 같은 종목 추가 시 합쳐지지 않음

### ISSUE THREAD

**Issue by yzooop** [100-hours-a-week/5-team-HRTH-ustock-fe#95]
##  버그 설명
같은 종목을 검색해서 추가등록하면 합쳐지지 않고 각자 뜬다. (새로고침을 하면 합쳐짐) 
<img width="385" alt="스크린샷 2024-08-25 오후 2 13 25" src="https://github.com/user-attachments/assets/16118f25-2640-4764-ba11-0647dc01161c">

## 재현하는 방법

동작을 재현하는 단계:

1. Go to '포트폴리오 상세 페이지'
2. Click on '+' & 종목 등록
3. See error

## 예상한 동작

예상했던 일에 대한 명확
<img width="378" alt="스크린샷 2024-08-25 오후 2 13 35" src="https://github.com/user-attachments/assets/f142494b-4153-4520-8cfb-b66bf07028f3">
하고 간결한 설명해주세요.
- 새로 추가하면 같은 종목끼리 합쳐져야 함

## 스크린샷 (옵션)

문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.

## 데스크톱(다음 정보를 작성해 주세요):

- OS: [예) iOS]
- Browser [예) chrome, safari]
- Version [예) 22]

## 추가적인 내용 (옵션):

여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by lucy726j** [comment]
수정 완료
