### ISSUE TITLE
[PC-Chrome-1920-포트폴리오 상세 페이지 > 종목 상세] 수익률과 수익금이 반영되지 않음

### ISSUE THREAD

**Issue by yzooop** [100-hours-a-week/5-team-HRTH-ustock-fe#96]
##  버그 설명
<img width="461" alt="스크린샷 2024-08-25 오후 2 13 13" src="https://github.com/user-attachments/assets/097597d1-920d-465a-a4ef-7bdfd6f0fd0b">
수량과 매수금액만 반영되고
수익률과 수익금은 새로고침해야 뜬다.

## 재현하는 방법

동작을 재현하는 단계:

1. Go to '포트폴리오 상세페이지'
2. Click on 'swipe창'
3. See error

## 예상한 동작
- 새로고침 없이 종목추가하면 수익률과 수익금이 떠야한다. 

## 스크린샷 (옵션)

문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.

## 데스크톱(다음 정보를 작성해 주세요):

- OS: [예) iOS]
- Browser [예) chrome, safari]
- Version [예) 22]

## 추가적인 내용 (옵션):

여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by lucy726j** [comment]
수정 완료
