### ISSUE TITLE
[PC-Chrome-1920-포트폴리오 상세종목 > 삭제모달] css margin

### ISSUE THREAD

**Issue by yzooop** [100-hours-a-week/5-team-HRTH-ustock-fe#98]
##  버그 설명

버그에 대한 명확하고 간결한 설명해주세요.
<img width="513" alt="스크린샷 2024-08-25 오후 2 51 30" src="https://github.com/user-attachments/assets/ca441ec6-3cf4-4ba3-a495-f23ca349f65c">
- margin top 조절 필요

## 재현하는 방법

동작을 재현하는 단계:

1. Go to '포트폴리오 상세조회'
2. Click on 'swipe 창'
3. Click on '삭제모달 클릭'

## 예상한 동작

예상했던 일에 대한 명확하고 간결한 설명해주세요.

- 예상동작 1
- 예상동작 2

## 스크린샷 (옵션)

문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.

## 데스크톱(다음 정보를 작성해 주세요):

- OS: [예) iOS]
- Browser [예) chrome, safari]
- Version [예) 22]

## 추가적인 내용 (옵션):

여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by Yeonsu00-12** [comment]
ㅎㅎ.. 이거 안됩니다....
