### ISSUE TITLE
[PC-Chrome-1920-종목 추가 매수 모달] 종목 추가 매수 가능 개수 제한

### ISSUE THREAD

**Issue by lucy726j** [100-hours-a-week/5-team-HRTH-ustock-fe#99]
##  버그 설명

✅  사용자가 종목 구매할 수 있는 최대 수량과 최대 금액을 5자리, 10자리로 제한해주세요

프론트에서 한 번 구매할 때의 최대 수량과 금액을 제한해도,
여러번 추가 매수하면 제한을 넘어서 종목 구매가 가능해집니다.

## 재현하는 방법
1. 종목 구매를 99999개, 9999999999원 한다.
2. 종목 추가매수를 99999개, 9999999999원 한다.
3. 종목의 무한 구매가 가능해지고, CSS가 깨진다.
 
## 예상한 동작

1. 구매 가능 개수, 금액을 초과하면 에러 메세지 반환 등으로 응답

## 스크린샷 (옵션)
<img width="767" alt="스크린샷 2024-08-25 오후 2 51 11" src="https://github.com/user-attachments/assets/5a8091eb-d49c-45cc-ba03-60699a469485">

## 데스크톱(다음 정보를 작성해 주세요):
- 브라우저 : 크롬

## 추가적인 내용 (옵션):

여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by Lcrescent3es** [comment]
개발/배포서버 분리 끝나면 push 하겠습니다

**Comment by Lcrescent3es** [comment]
-완-
